WIDTH = HEIGHT = 700
DIMENSION = 7
SQ_SIZE = WIDTH // DIMENSION
MAX_FPS = 5
IMAGES = {}
FILE_PATH_IMAGES = "images/"
FILE_EXTENSION = ".png"

CORNER_SQUARES = [(0, 0), (0, DIMENSION - 1), (DIMENSION - 1, 0), (DIMENSION - 1, DIMENSION - 1)]
ADJACENT_CORNER_SQUARES = [(0, 1), (1, 0), (0, DIMENSION - 2), (1, DIMENSION - 1), (DIMENSION - 2, 0), (DIMENSION - 1, 1), (DIMENSION - 2, DIMENSION - 1), (DIMENSION - 1, DIMENSION - 2)]
FAR_CORNER_SQUARES = [(0, 2), (2, 0), (0, DIMENSION - 3), (2, DIMENSION - 1), (DIMENSION - 3, 0), (DIMENSION - 1, 2), (DIMENSION - 3, DIMENSION - 1), (DIMENSION - 1, DIMENSION - 3)]

CENTRE_SQUARE = [(DIMENSION // 2, DIMENSION // 2)]
ADJACENT_CENTRE_SQUARE = [((DIMENSION // 2) - 1, DIMENSION // 2), ((DIMENSION // 2) + 1, DIMENSION // 2), (DIMENSION // 2, (DIMENSION // 2) + 1), (DIMENSION // 2, (DIMENSION // 2) - 1)]
FAR_CENTRE_SQUARE = [((DIMENSION // 2) - 2, DIMENSION // 2), ((DIMENSION // 2) + 2, DIMENSION // 2), (DIMENSION // 2, (DIMENSION // 2) + 2), (DIMENSION // 2, (DIMENSION // 2) - 2)]

SPECIAL_SQUARES = CORNER_SQUARES + CENTRE_SQUARE

PIECE_VALS = {'K': 4, 'P': 1}
WIN_VAL = 1000
DRAW_VAL = 0

RANKS_TO_ROWS = {"1": 6, "2": 5, "3": 4, "4": 3, "5": 2, "6": 1, "7": 0}
ROWS_TO_RANKS = {v: k for k, v in RANKS_TO_ROWS.items()}
FILES_TO_COLS = {"a": 0, "b": 1, "c": 2, "d": 3, "e": 4, "f": 5, "g": 6}
COLS_TO_FILES = {v: k for k, v in FILES_TO_COLS.items()}
