WIDTH = HEIGHT = 700
DIMENSION = 7
SQ_SIZE = WIDTH // DIMENSION
MAX_FPS = 5
IMAGES = {}
FILE_PATH_IMAGES = "images/"
FILE_EXTENSION = ".png"

CORNER_SQUARES = [(0, 0), (0, DIMENSION - 1), (DIMENSION - 1, 0), (DIMENSION - 1, DIMENSION - 1)]
ADJACENT_CORNER_SQUARES = [(0, 1), (1, 0), (0, DIMENSION - 2), (1, DIMENSION - 1), (DIMENSION - 2, 0), (DIMENSION - 1, 1), (DIMENSION - 2, DIMENSION - 1), (DIMENSION - 1, DIMENSION - 2)]
FAR_CORNER_SQUARES = [(0, 2), (2, 0), (0, DIMENSION - 3), (2, DIMENSION - 1), (DIMENSION - 3, 0), (DIMENSION - 1, 2), (DIMENSION - 3, DIMENSION - 1), (DIMENSION - 1, DIMENSION - 3)]

CENTRE_SQUARE = [(DIMENSION // 2, DIMENSION // 2)]
ADJACENT_CENTRE_SQUARE = [((DIMENSION // 2) - 1, DIMENSION // 2), ((DIMENSION // 2) + 1, DIMENSION // 2), (DIMENSION // 2, (DIMENSION // 2) + 1), (DIMENSION // 2, (DIMENSION // 2) - 1)]
FAR_CENTRE_SQUARE = [((DIMENSION // 2) - 2, DIMENSION // 2), ((DIMENSION // 2) + 2, DIMENSION // 2), (DIMENSION // 2, (DIMENSION // 2) + 2), (DIMENSION // 2, (DIMENSION // 2) - 2)]

SPECIAL_SQUARES = CORNER_SQUARES + CENTRE_SQUARE

